name: Generate API docs

on:
  push:
    branches:
      - ci_test
  pull_request: # for testing
  release:
    types: [published]

jobs:
  halo_api_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure Doxygen
        run: sed -i -e 's/@PROJECT_SOURCE_DIR@/..' ${{runner.workspace}}/ODLA/Doxyfile
