name: Generate API docs

on:
  push:
    branches:
      - ci_test
  pull_request: # for testing
  release:
    types: [published]

jobs:
  halo_api_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure Doxygen
        run: sed -i -e 's/@PROJECT_SOURCE_DIR@/../g' $GITHUB_WORKSPACE/ODLA/Doxyfile
      - name: Build HTML
        uses: mattnotmitt/doxygen-action@v1
        with:
          working-directory: "odla_docs"
          doxyfile-path: "$GITHUB_WORKSPACE/ODLA/Doxyfile"
          enable-latex: true
      - name: Publish
        run: ls ${{runner.workspace}}/odla_docs
